version: "2"

services:
  mqtt:
    build:
      context: .
      dockerfile: DockerfileMqtt
    volumes:
      - .:/proj
    command: bash -c "mosquitto & ./ci-to-mqtt.py"
    ports:
      - "80:80"
      - "1883:1883"
    environment:
      - MQTT_BROKER_HOST
      - MQTT_TOPIC
      - LOG_LEVEL

  rpi:
    build:
      context: .
      dockerfile: DockerfileRpi
    volumes:
      - .:/proj
      - /dev/gpiomem:/dev/gpiomem
    command: ./mqtt-to-led.py
    environment:
      - RED_CHAN
      - GREEN_CHAN
      - MQTT_BROKER_HOST
      - MQTT_TOPIC
      - LOG_LEVEL
    privileged: true

